google:
  name: Google Data APIs
  site: https://www.google.com
  request_token_url: https://www.google.com/accounts/OAuthGetRequestToken
  authorize_url: https://www.google.com/accounts/OAuthAuthorizeToken
  access_token_url: https://www.google.com/accounts/OAuthGetAccessToken

smartfm:
  name: smart.fm API
  site: http://api.smart.fm
  request_token_url: http://api.smart.fm/oauth/request_token
  authorize_url: http://smart.fm/oauth/authorize
  access_token_url: http://api.smart.fm/oauth/access_token

twitter:
  name: twitter API
  site: http://twitter.com
  request_token_url: http://twitter.com/oauth/request_token
  authorize_url: http://twitter.com/oauth/authorize
  access_token_url: http://twitter.com/oauth/access_token

my_sample:
  name: my sample
  site: http://localhost:3001
  request_token_url: http://localhost:3001/oauth/request_token
  authorize_url: http://localhost:3001/oauth/authorize
  access_token_url: http://localhost:3001/oauth/access_token
