google:
  name: Google Data APIs
  site: https://www.google.com
  request_token_url: https://www.google.com/accounts/OAuthGetRequestToken
  authorize_url: https://www.google.com/accounts/OAuthAuthorizeToken
  access_token_url: https://www.google.com/accounts/OAuthGetAccessToken

smartfm:
  name: smart.fm API
  site: http://api.smart.fm
  request_token_url: http://api.smart.fm/oauth/request_token
  authorize_url: http://smart.fm/oauth/authorize
  access_token_url: http://api.smart.fm/oauth/access_token

smartfm_dev:
  name: smart.fm API dev
  site: http://api.dev.iknow.co.jp
  request_token_url: http://api.dev.iknow.co.jp/oauth/request_token
  authorize_url: http://dev.smart.fm/oauth/authorize
  access_token_url: http://api.dev.iknow.co.jp/oauth/access_token