google:
  name: Google Data APIs
  site: https://www.google.com
  request_token_url: https://www.google.com/accounts/OAuthGetRequestToken
  authorize_url: https://www.google.com/accounts/OAuthAuthorizeToken
  access_token_url: https://www.google.com/accounts/OAuthGetAccessToken

iknow:
  name: iKnow! API
  site: http://api.iknow.co.jp
  request_token_url: http://api.iknow.co.jp/oauth/request_token
  authorize_url: http://www.iknow.co.jp/oauth/authorize
  access_token_url: http://api.iknow.co.jp/oauth/access_token